name: "AreaPods: Issue Triage"

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

on:
  issues:
    types: [opened, closed, transferred, reopened, assigned, unassigned, labeled, unlabeled, milestoned, demilestoned]

jobs:
  areapods:
    uses: jeffhandley/github-actions/.github/workflows/areapods.issue-triage.yml@main
    with:
      issue:    ${{ github.event.issue.number }}
      action:   ${{ github.event.action }}
      assignee: ${{ github.event.assignee.login }}
      label:    ${{ github.event.label.name }}
