name: "Issue Labeler: Author Issues"

on:
  issues:
    types: [opened]

  workflow_dispatch:
    inputs:
      issue:
        description: The issue number to process
        required: true
        type: number
      authors:
        description: The list of authors whose issues should get labeled (separated by spaces)
        required: true
      label:
        description: The label to apply
        required: true

jobs:
  issue-labeler:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: author-issues
        uses: jeffhandley/github-actions/actions/issue-labeler/authors@main
        with:
          issue:   ${{ inputs.issue || github.event.issue.number }}
          authors: ${{ inputs.authors || 'jeffhandley eilon heng-liu' }}
          label:   ${{ inputs.label || 'team-member' }}
