name: "Issue Labeler: Author Issues"

on:
  issues:
    types: [opened]

  workflow_dispatch:
    inputs:
      issue:
        description: The issue number to process
        required: true
        type: number
      authors:
        description: The authors whose issues get labeled (separated by spaces)
        required: true
      label:
        description: The label to apply for the specified authors
        required: true

jobs:
  issue-labeler:
    permissions:
      issues: write

    uses: jeffhandley/github-actions/.github/workflows/issue-labeler.authors.yml@main
    with:
      issue:   ${{ inputs.issue   || github.event.issue.number }}
      authors: ${{ inputs.authors || 'jeffhandley eilon heng-liu' }}
      label:   ${{ inputs.label   || 'team-member' }}
