name: "Labeler: Promote Issue Model"

on:
  workflow_dispatch:
    inputs:
      model_cache_key:
        description: "The cache key suffix to promote"
        type: string
        required: true

env:
  MODEL_PATH: labeler-cache/issue-model.zip
  MODEL_CACHE_KEY: github-ml-labeler/issues/model/${{ inputs.model_cache_key }}
  PROMOTION_CACHE_KEY: github-ml-labeler/issues/model/${{ inputs.repository || github.repository }}

jobs:
  promote-issue-model:
    permissions:
      actions: write

    steps:
      - name: "Restore model from cache"
        uses: jeffhandley/github-ml-labeler/.github/workflows/labeler-promote-issues.yml@main
    with:
      model_cache_key: ${{ inputs.model_cache_key }}
