name: "Labeler: Download Pull Requests"

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: "The GitHub token (defaults to action token)"
        type: string
      org_repo:
        description: "The org/repo to download data from (defaults to current repository)"
        type: string
      label_prefix:
        description: "Label prefix"
        type: string
        default: "area-"
      page_limit:
        description: "Max pages of items to download (100 items per page)"
        type: number
        default: 500
        required: true
      retries:
        description: "Comma-separated list of retry delays in seconds"
        type: string
        default: "30,30,30,300,300,3600"

jobs:
  labeler-download-pulls:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      pull-requests: read
    uses: jeffhandley/github-ml-labeler/.github/workflows/labeler-download-pulls.yml@main
      with:
        github_token: ${{ inputs.github_token || secrets.GITHUB_TOKEN }}
        org_repo: ${{ inputs.org_repo || github.repository }}
        label_prefix: ${{ inputs.label_prefix || 'area-' }}
        page_limit: ${{ fromJSON( inputs.page_limit || 500 )}}
        retries: ${{ inputs.retries || "30,30,30,300,300,3600" }}
