name: "Labeler: Model Pulls"

on:
  workflow_dispatch:
    inputs:
      data_cache_key:
        description: "The optional cache key suffix to use for loading the data (defaults to repository name)"
        type: string
      model_cache_key:
        description: "The optional cache key suffix to use for saving the model (defaults to repository name)"
        type: string

jobs:
  model-issues:
    uses: jeffhandley/github-ml-labeler/.github/workflows/labeler-model-pulls.yml@main
    with:
      data_cache_key: ${{ inputs.data_cache_key || github.repository }}
      model_cache_key: ${{ inputs.model_cache_key || github.repository }}
