name: "Labeler: Test Pull Model"

on:
  workflow_dispatch:
    inputs:
      github_token:
        description: "The GitHub token (defaults to action token)"
        type: string
      repository:
        description: "The org/repo to download data from (defaults to current repository)"
        type: string
      pull_limit:
        description: "Max number of items to include in the test"
        type: number
        default: 50000
        required: true
      label_prefix:
        description: "Label Prefix"
        type: string
        default: "area-"
        required: true
      threshold:
        description: "The minimum confidence score for a label prediction"
        type: number
        default: "0.75"
        required: true
      default_label:
        description: "Default Label (leave blank for no default label)"
        type: string
        default: "needs-area-label"
      model_cache_key:
        description: "The optional cache key suffix to use for loading the model (defaults to repository name)"
        type: string

jobs:
  test-pulls:
    uses: jeffhandley/github-ml-labeler/.github/workflows/test-pulls.yml@main
    with:
      github_token: ${{ inputs.github_token || github.token }}
      repository: ${{ inputs.repository || github.repository }}
      pull_limit: ${{ fromJSON( inputs.pull_limit || 50000 ) }}
      label_prefix: ${{ inputs.label_prefix || 'area-' }}
      threshold: ${{ fromJSON( inputs.threshold || 0.75 ) }}
      default_label: ${{ inputs.default_label || 'needs-area-label' }}
      model_cache_key: ${{ inputs.model_cache_key || github.repository }}
