name: "Labeler: Predict Issue Label"

on:
  issues:
    types: [opened, edited, transferred]

  workflow_dispatch:
    inputs:
      number:
        description: "Issue Number(s)"
        type: string
        required: true
      label_prefix:
        description: "Label Prefix"
        type: string
        default: "area-"
        required: true
      threshold:
        description: "The minimum confidence score for a label prediction"
        type: number
        default: "0.40"
        required: true
      default_label:
        description: "Default Label (leave blank for no default label)"
        type: string
        default: "needs-area-label"
      model_cache_key:
        description: "The optional cache key suffix to use for loading the model (defaults to repository name)"
        type: string

jobs:
  predict-issue:
    permissions:
      issues: write
    uses: jeffhandley/github-ml-labeler/.github/workflows/predict-issue.yml@main
    with:
      number: ${{ inputs.number || github.event.issue.number }}
      label_prefix: ${{ inputs.label_prefix || 'area-' }}
      threshold: ${{ fromJSON( inputs.threshold || 0.40 ) }}
      default_label: ${{ inputs.default_label || 'needs-area-label' }}
      model_cache_key: ${{ inputs.model_cache_key || github.repository }}
