name: "Labeler: Promote Pull Model"

on:
  workflow_dispatch:
    inputs:
      model_cache_key:
        description: "The cache key suffix to promote"
        type: string
        required: true

env:
  MODEL_PATH: labeler-cache/pull-model.zip
  MODEL_CACHE_KEY: github-ml-labeler/pulls/model/${{ inputs.model_cache_key }}
  PROMOTION_CACHE_KEY: github-ml-labeler/pulls/model/${{ inputs.repository || github.repository }}

jobs:
  promote-pull-model:
    steps:
      - name: "Restore model from cache"
        uses: jeffhandley/github-ml-labeler/.github/workflows/labeler-promote-pulls.yml@main
    with:
      model_cache_key: ${{ inputs.model_cache_key }}
